name: thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.10.11
      - aiosignal==1.3.2
      - aistudio-sdk==0.3.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backoff==2.2.1
      - bce-python-sdk==0.9.46
      - certifi==2025.4.26
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - click==8.3.0
      - colorama==0.4.6
      - colorlog==6.9.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - exceptiongroup==1.3.0
      - filelock==3.18.0
      - fonttools==4.58.0
      - frozenlist==1.6.0
      - fsspec==2025.5.1
      - future==1.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.1
      - idna==3.10
      - imageio==2.37.0
      - imagesize==1.4.1
      - inference-sdk==0.49.1
      - Jinja2==3.1.6
      - jiwer==4.0.0
      - joblib==1.5.2
      - kiwisolver==1.4.8
      - lazy_loader==0.4
      - Levenshtein==0.27.1
      - MarkupSafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.3
      - modelscope==1.30.0
      - mpmath==1.3.0
      - multidict==6.4.3
      - mypy_extensions==1.1.0
      - networkx==3.4.2
      - numpy==2.2.5
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - opt-einsum==3.3.0
      - packaging==25.0
      - paddleocr==3.2.0
      - paddlepaddle==3.2.0
      - paddlex==3.2.1
      - pandas==2.3.2
      - pillow==11.2.1
      - prettytable==3.16.0
      - propcache==0.3.1
      - protobuf==6.32.1
      - psutil==7.1.0
      - py-cpuinfo==9.0.0
      - pyclipper==1.3.0.post6
      - pycryptodome==3.23.0
      - pydantic==2.11.9
      - pydantic_core==2.33.2
      - pyparsing==3.2.3
      - pypdfium2==4.30.0
      - pytesseract==0.3.13
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-Levenshtein==0.27.1
      - pytz==2025.2
      - pywin32==311
      - PyYAML==6.0.2
      - RapidFuzz==3.14.1
      - requests==2.32.3
      - ruamel.yaml==0.18.15
      - ruamel.yaml.clib==0.2.14
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shapely==2.1.2
      - six==1.17.0
      - sniffio==1.3.1
      - supervision==0.25.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torch==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - typing_extensions==4.13.2
      - tzdata==2025.2
      - ujson==5.11.0
      - urllib3==2.4.0
      - wcwidth==0.2.14
      - yarl==1.20.0
